### ISSUE TITLE
Solution of lion states problem

### ISSUE THREAD

**Issue by eugeny-dementev** [2gisprojectT/for-homeworks#1]
Решения задачи со львом засыпающим на голодный желудок при виде дерева.
Три файлика в каталоге intreview Файл lion с описанием класса льва. Он создается и ему на вход подается компания для диалога через метод meet(company). Файл states с состояниями льва. Работа с ними не подразумевает прямого использования. Файл test_lion с юнит тестами реакции льва со всех возможными состояниями на партнеров для встречи. Ну собственно его и запускать. https://github.com/2gisprojectT/dementyev-lastfm/tree/master/interview

**Comment by shiron** [comment]
Итак, у меня комментарии только по тестам)
1) Отдельные случаи лучше разбивать по отедльным кейсам, так и код чище и поддерживать его удобнее, например: test_meet_tree и т.д.
2) Наверное стоит написать тест на конструктор льва, поскольку в нем инитятся некоторые значения

**Comment by eugeny-dementev** [comment]
Поправил. Разнес тесты встреч по каждому отдельному случаю. Добавил в конструктор льва параметр для задания начального состояния лёвы и тесты для этого.

**Comment by shiron** [comment]
Ок, закрываю)
