### ISSUE TITLE
Тест Selenium

### ISSUE THREAD

**Issue by eltray** [2gisprojectT/for-homeworks#10]
Натестил)
https://github.com/2gisprojectT/traystor-info2gis/commit/b16025a002e17754c499f582122202e621323bed

**Comment by shiron** [comment]
Добавь каких-нибудь проверок в тест, в Selenium IDE тоже есть asserts.

**Comment by eltray** [comment]
Исправил
https://github.com/2gisprojectT/traystor-info2gis/tree/master/2.HW_TestSelenium

**Comment by shiron** [comment]
окей, закрываю)
Но ты там глянь, в файле есть проблема с кодировкой.
