### ISSUE TITLE
Selenium IDE test cases for Twitter

### ISSUE THREAD

**Issue by denkj** [2gisprojectT/for-homeworks#11]
[Смотреть здесь](https://github.com/2gisprojectT/kaygorodov-twitter/tree/master/SeleniumIDE-Tests)

Самая важную функцию отправки твитов протестировать не удалось. Text box для твита это div, а средствами Selenium IDE записать в div не получилось (stackoverflow говорит, что это вообще невозможно).
И кнопка Follow отвечает за несколько состояний сразу, поэтому последний тест немного не data-driven.

**Comment by shiron** [comment]
Засчитано. Первые тесты с ассертами:)
