### ISSUE TITLE
ДЗ Лев

### ISSUE THREAD

**Issue by beta-tank** [2gisprojectT/for-homeworks#13]
Кодлежит здесь https://github.com/2gisprojectT/komissarov-habrahabr/tree/master/2_lion
Состояния, входные объекты и действия представлены иерархией классов. Автомат задан таблицей.

**Comment by shiron** [comment]
Комментарии по тестам: лучше не использовать сложную логику, рандомные значения и не усложнять юнит-тесты. Если необходимо протестировать несколько вариаентов входных значений, то на каждый из них лучше написать отдельные тесты.
Так будет более понятно и легче с точки зрения поддержки в будущем.

**Comment by beta-tank** [comment]
Разбил часть тестов на несколько, убрал рандом и уменьшил циклы. Совсем избавиться от сложной логики не удалось, потому что всё-таки нужно проверить правильность реакции автомата.

**Comment by shiron** [comment]
Окей, закрываю.
