### ISSUE TITLE
DZ - Selenium IDE

### ISSUE THREAD

**Issue by Galliwspain** [2gisprojectT/for-homeworks#14]
Добавил [тесты](https://github.com/2gisprojectT/semenov-drom/tree/master/first%20tests%20Selenium)

**Comment by shiron** [comment]
Аналогично Login лучше разбить на разные тесты, а в тесты на регистрацию добавить asserts (это же тесты:))

**Comment by Galliwspain** [comment]
Добавил LogInNOK, добавил assetы)[вот](https://github.com/2gisprojectT/semenov-drom/tree/master/first%20tests%20Selenium)

**Comment by shiron** [comment]
Окей, закрываю.
