### ISSUE TITLE
Selenium IDE Test Suite for Forexfactory

### ISSUE THREAD

**Issue by PunkBASSter** [2gisprojectT/for-homeworks#15]
https://github.com/2gisprojectT/shpilev-forexfactory/tree/master/Selenium_IDE_Homework
test_Login.html - тест авторизации для разминки.

test_PasswordChange.html - тест изменения пароля. Шаги: 
1. Авторизация; 
2. Смена пароля; 
3. Логаут; 
4. Авторизация с новым паролем; 
5. Смена пароля на старый; 
6. Логаут.

test_EmailChange.html - тест изменения почты. Шаги: 
1. Авторизация; 
2. Смена почты; 
3. Проверка указания нового адреса в настройках профиля; 
4. Смена почты на старую; 
5. Проверка указания старого адреса в настройках профиля;
6. Логаут.

**Comment by shiron** [comment]
Все ок, единственное - в тесты нужно добавить asserts, это же тесты)

**Comment by PunkBASSter** [comment]
Исправь, если я ошибаюсь, но:
1. В изменении почты Ассерты есть.
2. В изменении пароля Ассерты, по-моему, пихать некуда и незачем, т.к. ожидаемый результат изменения пароля -- это авторизация с только что измененным паролем (без нее тест не выполнится). 
3. Тест авторизации -- чисто вспомогательный скрипт, который сэкономил время при создании и отладке двух других кейсов.
P.S. В процессе выполнения ДЗ я, кажется, понял, почему Selenium IDE не торт.

**Comment by shiron** [comment]
Да, но хорошие тесты, если падают, то по ассертам, плохие - по каким-нибудь другим причинам.
Поэтому в случае авторизации - это проверка, что пользователь залогинился.

**Comment by PunkBASSter** [comment]
Вроде понял, то есть при авторизации нужно ассертнуть что-то, что недоступно без авторизации. Акей, видимо, это общепринятый стандарт, и надо его придерживаться, исправил!
https://github.com/2gisprojectT/shpilev-forexfactory/tree/master/Selenium_IDE_Homework

**Comment by shiron** [comment]
Угу, закрываю)
