### ISSUE TITLE
Тестирование Льва

### ISSUE THREAD

**Issue by vadim-uvarov** [2gisprojectT/for-homeworks#16]
Смотреть каталог https://github.com/2gisprojectT/uvarov-vk/tree/master/state_machine

В Lion_class.py реализовано поведение Льва:
 **init** - инициализация в состоянии "голодный" или "сытый"
 **shiftToNextState(Input)** - переход в новое состояние по входному символу Input с возвращением наблюдаемого символа

В TestLion.py находятся юнит-тесты на инициализацию и переход в след. состояние при разных входных данных и исходных состояниях

**Comment by shiron** [comment]
Закрываю, но первый и последний тесты лучше разделить на два кейса, поскольку в обоих случаях проверяются два варианта входных значений.
