### ISSUE TITLE
Selenium: 1 дз - vk.com

### ISSUE THREAD

**Issue by vadim-uvarov** [2gisprojectT/for-homeworks#17]
См. три теста здесь: https://github.com/2gisprojectT/uvarov-vk/tree/master/selenium_first_try
**login_correct**                    - вход по верному логину/паролю
**login_uncorrect**                - вход по верному неверному паролю
**writeNewPostInGroup**       - написание нового поста в группе

Сначала долгое время пытался протестировать отправку сообщения и прикрепление аттачментов к сообщению, но не удалось, т. к. не смог обратится к полю ввода текста сообщения, а при добавлении фото оно почему-то открывалось в альбоме, вместо того, чтобы прикрепиться.

Неудавшиеся тесты:
**messages_attachements.html** - аттачмент-фото
**messages_send_text.html** - отправка текста

**Comment by shiron** [comment]
Аттачменты с помощью Селениум ИДЕ протестировать нельзя. Если спросишь на след. паре, объясню почему:)
По тестам - ок, закрываю. Единственное, там в одном тесте кажется ассертов не было.
