### ISSUE TITLE
ДЗ Selenium

### ISSUE THREAD

**Issue by beta-tank** [2gisprojectT/for-homeworks#18]
Тесты лежат здесь https://github.com/2gisprojectT/komissarov-habrahabr/tree/master/3_selenium_base
login - Авторизация на сайте и проверка успешного завершения. Нужно подставить корректные логин и пароль.
search_short_string - поиск по строке короче допустимой. Проверяется пустота поисковой выдачи.
search_string - поиск фразы "windows 10". Проверяется наличие определённой статьи в выдаче.

**Comment by shiron** [comment]
Все окей, закрываю)
