### ISSUE TITLE
Решение задачи со львом

### ISSUE THREAD

**Issue by terekhovyes** [2gisprojectT/for-homeworks#2]
Перенес Issue :)
Решил задачу. Все тесты проходят. Файлы находятся здесь:
https://github.com/2gisprojectT/terehov-soundcloud/tree/master/Day0810_HW_LionState
actions.py — действия льва
states.py — состояния льва
inputs.py — возможные входные значения
lion.py — сам лев, автомат состояний
test_lion.py — тесты автомата состояний «Lion»

**Comment by shiron** [comment]
С кодом, в принципе, все ок) 
По тестам:
1) Желательно не делать сложную логику в тестах с циклами и прочим, поскольку тесты должны быть легко читаемыми. По ним должно быть сразу понятна вся логика приложения.
Поэтому на текущем этапе лучше тест test_giving_correct_inputs разбить на несколько.
2) Наверное следует написать тест и на конструктор льва, поскольку в нем тоже есть логика.

**Comment by terekhovyes** [comment]
1) Добавил тест конструктора
2) test_giving_correct_inputs превратился в test_hungry_lion_for_exceptions и test_fed_lion_for_exceptions вообще без циклов и rand-ов

**Comment by shiron** [comment]
Ок, закрываю.
