### ISSUE TITLE
Selenium

### ISSUE THREAD

**Issue by MihaZiK** [2gisprojectT/for-homeworks#21]
Лежат здесь: https://github.com/2gisprojectT/shalakin-leagueoflegends/tree/master/SeleniumIDE

Авторизация и поиск. Пустые поля вроде и признает, а вроде и нет, не совсем понял.

P.S. По тест-дизайну отправил на почту

**Comment by shiron** [comment]
Добавь в тесты ассерты, это же тесты)

**Comment by MihaZiK** [comment]
Исправил

**Comment by shiron** [comment]
Ок, закрываю.
