### ISSUE TITLE
Selenium IDE Tests

### ISSUE THREAD

**Issue by DjonnyD** [2gisprojectT/for-homeworks#22]
https://github.com/2gisprojectT/akulov-aliexpress/tree/master/selenium
 minmax.html  - Тест на проверку границ цены в отсортированном списке товаров 
корзина.html -   Тест на проверку добавления товаров в корзину
удаление из корзины.html   -Тест на проверку удаление товаров из корзину

**Comment by shiron** [comment]
Окей, закрываю)
