### ISSUE TITLE
Selenium тесты

### ISSUE THREAD

**Issue by terekhovyes** [2gisprojectT/for-homeworks#24]
5 всяких разных тестов на функционал soundcloud.com:
https://github.com/2gisprojectT/terehov-soundcloud/tree/master/Day1010_HW_Selenium

**Comment by shiron** [comment]
Там только сюит выложился, который просто все тесты объединяет. Выложи еще сами тесты плиз)

**Comment by terekhovyes** [comment]
Блин :( Пришлось переписать заново — теперь выложил всё.

**Comment by shiron** [comment]
Все окей, закрываю)
