### ISSUE TITLE
Задача про льва

### ISSUE THREAD

**Issue by julTitova** [2gisprojectT/for-homeworks#25]
Паша, посмотри задачу про льва, и тест к ней.
https://github.com/julTitova/Lion
Файлы Lion.py и Test.py

**Comment by shiron** [comment]
По тестам: они должны покрывать максимальное количество случаев:)
Для каждого случая - свой тест.

**Comment by julTitova** [comment]
Паша, посмотри исправленный вариант. https://github.com/julTitova/Lion
Файлы: Test - проверяет метод full() с помощью возможных эквивалентных классов;
Test2 - проверяет метод hungry() с помощью возможных эквивалентных классов;
Test3 - проверяет, какие значения может принимать Object_view

**Comment by shiron** [comment]
Окей, уже лучше:) Можно еще поправить:
1) Все тесты можно переместить в один класс Test.py, но вразные методы класса
2) Ассерты есть только в Test3.py, а по-хорошему должны быть в любом тесте))
3) Если в тесте проверяется три разных случая, то лучше это разбить на три тестовых метода в классе

**Comment by julTitova** [comment]
Паша, объединила все тесты в 1 класс Main_test.py, для каждого экземпляра класса (тестового случая) выполняется - ассерт, методы full() и hungry().

**Comment by shiron** [comment]
Юля, уже гораздо лучше) Некоторые моменты давай я тебе во вторник лучше покажу сразу на примере, чтобы ты потом все быстренько поправили.

**Comment by julTitova** [comment]
Паша, все поправила. Файл Main_test.py Для каждого тестового случая свой метод.

**Comment by shiron** [comment]
Окей, закрываю)
