### ISSUE TITLE
SeleniumWebDriver

### ISSUE THREAD

**Issue by e7now** [2gisprojectT/for-homeworks#27]
https://github.com/2gisprojectT/semenov-pikabu/blob/master/03%20selenium/selenium/main.py

Написал тест для поля ввода email на pikabu.ru

**Comment by shiron** [comment]
А чего нет отступов в файле?

**Comment by e7now** [comment]
Не знаю. Все отступы вроде на месте.

**Comment by shiron** [comment]
Ага, все ок, закрываю)
