### ISSUE TITLE
SeleniumWD

### ISSUE THREAD

**Issue by eltray** [2gisprojectT/for-homeworks#28]
Домашняя работа на пятницу 17.10.14
https://github.com/2gisprojectT/traystor-info2gis/tree/master/3.HW_SeleniumWebDriver

**Comment by shiron** [comment]
Окей, закрываю)

**Comment by shiron** [comment]
А где прошлая?)

**Comment by eltray** [comment]
да у меня там тупняк) если что, завтра к тебе подойду с вопросами)
