### ISSUE TITLE
Задача со львом

### ISSUE THREAD

**Issue by MihaZiK** [2gisprojectT/for-homeworks#3]
Лежит здесь: https://github.com/2gisprojectT/shalakin-leagueoflegends/tree/master/LionProject
Lion.py - файл со львом
LionTest.py - файл с тестами

**Comment by shiron** [comment]
В тестах должны быть проверки, assert-ы всякие. Иначе это уже не тесты:)

**Comment by MihaZiK** [comment]
Исправил

**Comment by shiron** [comment]
Окей, закрываю:)

**Comment by shiron** [comment]
И пока еще висит прошлая домашка с тест-дизайном:)
