### ISSUE TITLE
Тестирование с помощью драйвера Selenium: vk.com

### ISSUE THREAD

**Issue by vadim-uvarov** [2gisprojectT/for-homeworks#31]
https://github.com/2gisprojectT/uvarov-vk/blob/master/3)%20selenium_driver/vk_messages.py

Здесь тестируется отправка текстового сообщения (предварительно производится вход в vk.com)
Предусловия: должен быть хотя бы один друг.

**Comment by shiron** [comment]
Окей, закрываю)
