### ISSUE TITLE
SeleniumWebDriver

### ISSUE THREAD

**Issue by terekhovyes** [2gisprojectT/for-homeworks#32]
https://github.com/2gisprojectT/terehov-soundcloud/blob/master/Day1610_HW_SeleniumWebdriver/soundcloud_test.py
Потестировал, что при поиске треков сайт выводит информацию и кнопки управления для найденного трека — там целая куча элементов)

**Comment by shiron** [comment]
ааа))) чего с отступами?

**Comment by terekhovyes** [comment]
А конкретней?) С какими отступами что не так?))

**Comment by shiron** [comment]
С отступами разобрались:) Теперь есть еще парочка комментариев:
1) try-catch лучше так не делать, точнее лучше вообще не вставлять в тест. Если элемент не найдется, то тест и так упадет.
2) Ожидание элемента можно сделать вот так driver.implicitly_wait(30). Точнее эта команда поставить таймаут на ожидание любого элемента на 30 секунд. Если за это время он не найдется, то тест провалится.
3) В тесте нужны assert-ы)

**Comment by terekhovyes** [comment]
Ну вот что-то переделал: 1 и 2 прям исправил, ну а 3 — теперь есть какие-то assert-ы))

**Comment by shiron** [comment]
Окей, я закрываю)
Старый тест лучше совсем удалить)
