### ISSUE TITLE
Selenium WebDriver

### ISSUE THREAD

**Issue by la0rg** [2gisprojectT/for-homeworks#33]
Тесты из SeleniumIDE теперь и на <a href="https://github.com/2gisprojectT/lanbin-coursera/tree/master/selenium_webdriver">Python</a>

**Comment by shiron** [comment]
Окей, закрываю) 
Но второй тест падает с error:
NoSuchElementException: Message: u'Unable to locate element: {"method":"link text","selector":"Courses"}' ; Stacktrace:

**Comment by la0rg** [comment]
У меня успевало прогрузиться, видимо, нужно было тоже ожидание элемента установить)
