### ISSUE TITLE
Selenium webdriver test

### ISSUE THREAD

**Issue by eugeny-dementev** [2gisprojectT/for-homeworks#38]
https://github.com/2gisprojectT/dementyev-lastfm/tree/master/pylenium_tests

**Comment by shiron** [comment]
Окей, я закрываю. Но у меня есть парочка комментариев:
1) Чтобы проверить есть ли какой-то элемент на странице, то вместо 
assert driver.find_element_by_css_selector("#resultsSummary") лучше использовать:
self.assertTrue(driver.find_element_by_css_selector("#resultsSummary").is_displayed())
Т.к. в этом случае проверяется не только наличие элемента, но и видимость его дял пользователя.
2) Лишний код, спрятанный в комментарии, лучше удалять:)
