### ISSUE TITLE
Selenium IDE

### ISSUE THREAD

**Issue by julTitova** [2gisprojectT/for-homeworks#39]
Паша, посмотри тесты Selenium IDE по ссылке:https://github.com/2gisprojectT/titova-lingualeo/tree/master
Там 4 теста:  Authorization.html, Password_recovery.html,  Find_word.html, Find_Add_Delete.html и файл "readme" с пояснениями к ним.

**Comment by shiron** [comment]
С самими тестами все ок)
Единственное, в тестах должны быть assert-ы, т.е. проверки. Посмотри инфу про Selenium IDE, в нем есть assert-ы.

**Comment by julTitova** [comment]
Изменила все тесты, добавила ассерты 
ссылка:
https://github.com/2gisprojectT/titova-lingualeo/tree/master

**Comment by shiron** [comment]
Ok)
