### ISSUE TITLE
Problem about a Lion

### ISSUE THREAD

**Issue by denkj** [2gisprojectT/for-homeworks#4]
[Смотреть здесь](https://github.com/2gisprojectT/kaygorodov-twitter/tree/master/FSM-Lion)

**FSM** - безымянный конечный автомат
**Lion** - конечный автомат льва, связан композицией с классом FSM
**Lion_Test** - unit-тесты

**Comment by shiron** [comment]
Тесты лучше делать атомарными. Например, test_init проверяет по сути три разных кейса, поэтому лучше их разделить на разные тесты. То же самое и с другими кейсами.
А еще бы я тесты на сам конечный автомат написал:)

**Comment by denkj** [comment]
Все поправил. [Смотреть](https://github.com/2gisprojectT/kaygorodov-twitter/tree/master/FSM-Lion)

**Comment by shiron** [comment]
Окей, закрываю)
