### ISSUE TITLE
AliWebdriver

### ISSUE THREAD

**Issue by DjonnyD** [2gisprojectT/for-homeworks#40]
https://github.com/2gisprojectT/akulov-aliexpress/tree/master/AliWebDriver

<h5>TestAliexpress.py:</h5>

класс <b>TestMinMaxSD</b> - тест на проверку правельности сортировки товаров по цене в указанном диапазоне
класс <b>TestAddToBasket</b> - тест на проверку добавления и удаление из корзины. Пришлось запихать все в однин метод, т.к. если методы тестов будут разные, то метод удаления из корзины всегда будет провален, из-за того,что в корзине не будет товаров
<h5>Отчет о тестах.txt</h5> - з.ы. нашел баг...хотя похож на спец. задумку...

**Comment by shiron** [comment]
Окей, закрываю)
небольшой комментарий по вейтерам.
Можно сделать так в начале теста driver.implicitly_wait(30) и у него автоматически будет таймаут в 30 сек на поиск любого элемента. Если за 30 секунд не появится, то тест упадет.
