### ISSUE TITLE
HomeWork

### ISSUE THREAD

**Issue by HeyKote** [2gisprojectT/for-homeworks#43]
Привет, проверь пожалуйста SileniumIDE и SeleniumPython.

**Comment by shiron** [comment]
Ссылку на репу плиз.

**Comment by HeyKote** [comment]
Silenium IDE  https://github.com/2gisprojectT/vorontsov-youtube/tree/master/SeleniumIDEyoutubeTesting

Selenium Python https://github.com/2gisprojectT/vorontsov-youtube/tree/master/FirstTestSeleniumPythonTestting

**Comment by shiron** [comment]
По Selenium IDE и selenium тестам на python: в тесты нужно добавить проверки (assert-ы).
И еще по второй домашке вместе с тестами на Selenium IDE нужно было решить задачу про льва.

**Comment by HeyKote** [comment]
Добавил ассерты 
https://github.com/2gisprojectT/vorontsov-youtube/blob/master/FirstTestSeleniumPythonTestting/main.py

https://github.com/2gisprojectT/vorontsov-youtube/tree/master/SeleniumIDEyoutubeTesting

p.s лев скоро скоро)

**Comment by shiron** [comment]
Ок, жду льва)
