### ISSUE TITLE
Второй тест кейс 2GIS

### ISSUE THREAD

**Issue by terekhovyes** [2gisprojectT/for-homeworks#44]
Вот код самого теста:
https://github.com/2gisprojectT/terehov-soundcloud/blob/master/Day2110_2GISCases/online/tests/transport_search_test.py

Объект с результатом прокладки маршрута:
https://github.com/2gisprojectT/terehov-soundcloud/blob/master/Day2110_2GISCases/online/helpers/route_results.py

И блок поиска расширился новым функционалом:
https://github.com/2gisprojectT/terehov-soundcloud/blob/master/Day2110_2GISCases/online/helpers/search_bar.py

**Comment by shiron** [comment]
Окей, все гуд)
