### ISSUE TITLE
дз - паттерны - сайт 2гис

### ISSUE THREAD

**Issue by vadim-uvarov** [2gisprojectT/for-homeworks#46]
https://github.com/2gisprojectT/uvarov-vk/tree/master/4)%20patterns_2gis
1) тест "ссылки"
2) тест "поиска маршрута"

**Comment by shiron** [comment]
Окей, гуд, закрываю. Комментарий по поводу isFound в https://github.com/2gisprojectT/uvarov-vk/blob/master/4)%20patterns_2gis/helpers/path_result.py
Если элемент не будет найден, то выпадет эксепшен и else не сработает, поэтмоу нужно сделать так:
try:
    driver.find_element_by_css('css')
    return true
except:
    return false

**Comment by vadim-uvarov** [comment]
Так там же у меня **find_elementS**. Разве так не сработает?
Если хотя бы 1 элемент не найден, то он выдаст пустой список.
"if" проверяет пустоту списка там. 
Я проверял, работает, даже когда элемент не находится.
