### ISSUE TITLE
Дз с с лекции по паттернам

### ISSUE THREAD

**Issue by eugeny-dementev** [2gisprojectT/for-homeworks#47]
https://github.com/2gisprojectT/dementyev-lastfm/tree/master/online

Структура сохранена, добавлены объекты helpers 
- компонента extras: extras_bar.py, в search_bar.py добавлен метод извлечения строки поиска
- компонента route: route_bar.py

В page.py добавлены соответствующие методы для работы с компонентами.

**Comment by shiron** [comment]
Окей, гуд, закрываю. Комментарий по driver.implicitly_wait(10): его достаточно один раз вызвать и ожидания будут навешаны на все поиски элементво в тесте.
