### ISSUE TITLE
ДЗ 2 Теста для 2GIS

### ISSUE THREAD

**Issue by DjonnyD** [2gisprojectT/for-homeworks#48]
https://github.com/2gisprojectT/akulov-aliexpress/tree/master/3block/online

добавленные модули:
/helpers/extras_group.py - Класс экстра группы( расшарить, скачать и т.п.) 
/helpers/module_share.py - Класс окошка "поделиться"
/helpers/search_result_route.py - Класс результата поиска маршрута

**Comment by shiron** [comment]
Окей, гуд, закрываю.
