### ISSUE TITLE
2gis patterns - 1

### ISSUE THREAD

**Issue by la0rg** [2gisprojectT/for-homeworks#49]
Added 3 new components and changed some:
<a href="https://github.com/2gisprojectT/lanbin-coursera/tree/master/test_framework_1">code</a>

**Comment by shiron** [comment]
Вся работа с драйвером в тестах должна быть либо в компонентах, ли в пейджобжектах.
Например, открытие вкладки можно спрятать в отдельный метод в SearchBar:
#open new tab, use received link
body = driver.find_element_by_tag_name("body")
body.send_keys(Keys.CONTROL + 't')

**Comment by la0rg** [comment]
Исправил.

**Comment by shiron** [comment]
Окей, закрываю)
