### ISSUE TITLE
Конечный автомат состояний льва

### ISSUE THREAD

**Issue by PunkBASSter** [2gisprojectT/for-homeworks#5]
https://github.com/2gisprojectT/shpilev-forexfactory/tree/master/FSM_Lion
fsm.py - файл класса cFsm - конечный автомат (на основе вложенных списков)
lion.py - файл класса cLion - лев на основе cFsm
UntiTest_fsm.py и UnitTest_cLion - юнит-тесты представленных классов

**Comment by shiron** [comment]
Окей, закрываю:)
Только маленький комментарий оставлю: тест на инит льва лучше разделить на два теста, поскольку там два кейса проверяются.
