### ISSUE TITLE
ДЗ Тесты 2Gis

### ISSUE THREAD

**Issue by beta-tank** [2gisprojectT/for-homeworks#50]
Добавил тесты на расшаривание ссылки и проверку построения проезда. Лежат [здесь](https://github.com/2gisprojectT/komissarov-habrahabr/tree/master/5_selenium_2gis/online)
Дописан класс панели поиска, добавленны компоненты панелей расшаривания и результатов построения маршрута.

**Comment by shiron** [comment]
Окей, гуд, закрываю.
