### ISSUE TITLE
Паттерны 2gis

### ISSUE THREAD

**Issue by MihaZiK** [2gisprojectT/for-homeworks#54]
Лежит здесь: https://github.com/2gisprojectT/shalakin-leagueoflegends/tree/master/online

**Comment by shiron** [comment]
а чего один тест закомментирован?

**Comment by MihaZiK** [comment]
Чтобы каждый раз не запускать оба, когда второй писал не хотелось каждый раз на первый смотреть сначала)

**Comment by shiron** [comment]
Ок, закрываю)
