### ISSUE TITLE
Домашка по паттернам

### ISSUE THREAD

**Issue by terekhovyes** [2gisprojectT/for-homeworks#55]
5 тестов здесь:
https://github.com/2gisprojectT/terehov-soundcloud/tree/master/Day2810_HW_SoundcloudPatterns/tests
1. Тестим, что дополнительная строка поиска сохраняет значение основной с главной страницы
2. Проверяем, что у всех людей в поиске есть кнопка «Follow»
3. Смотрим, что в заголовке плеера правильный title песни
4. Глядим, что в поиске есть все 5 возможных категорий
5. Узреваем, появляется ли строка для ввода комментария по клику на песню

2 странички:
https://github.com/2gisprojectT/terehov-soundcloud/tree/master/Day2810_HW_SoundcloudPatterns/pages
1. Главная
2. Страница с результатами поиска

6 доп. компонентов:
https://github.com/2gisprojectT/terehov-soundcloud/tree/master/Day2810_HW_SoundcloudPatterns/components
1. Дополнительная строка поиска
2. Найденный человек
3. Найденный трек
4. Плеер в нижней части экрана
5. Строка поиска в заголовке
6. Категории на страничке результатов поиска

**Comment by shiron** [comment]
Ок, гуд, закрываю)
На будущее два маленьких комментария:
1) sleep-ы таки лучше не использовать, потому что они могут не сработать на другой машине или при другой скорости сети
2) для тестов можно тоже сделать базовый класс, в который вынести методы setUpClass и tearDownClass
