### ISSUE TITLE
Дз паттерны

### ISSUE THREAD

**Issue by DjonnyD** [2gisprojectT/for-homeworks#56]
https://github.com/2gisprojectT/akulov-aliexpress/tree/master/AliTests_3block
4 страницы:
/Page_Cart - все для страницы корзины
/Page_Goods - все для страницы товара
/Page_Main - главная страница
/Page_Search_Result - страница результатов

до всех этих страница можно достучаться через /Pages
тесты в /tests/AliTest.py
test_1- тест на проверку поиску с заданными границами цены
test_2- тест на проверку кореектности подсчета итоговой цены
test_3 - тест на удаление товаров из корзины
test_4 - тест на добавление товаров в корзину
test_5 - тест на правильное добавление в корзину количества товара

**Comment by shiron** [comment]
Окей, гуд, закрываю)
Единственное по организации страничек - лучше было сгрузить в одну папку.
/pages
/components
/tests
Как-то так) А компоненты могут пересипользоваться между разными страницами.
