### ISSUE TITLE
Лев дз(Обновление)

### ISSUE THREAD

**Issue by DjonnyD** [2gisprojectT/for-homeworks#6]
https://github.com/2gisprojectT/akulov-aliexpress/tree/master/Lion
 fsm-data - иходные данные для конечного автомата;
 Lion - реализация поведения льва;
 table_fsm - таблица правил конечного автомата; 
 LionTest - тестирование поведения льва

**Comment by shiron** [comment]
Конечно не совсем идеальная реализация конечного автомата, но даю комментарии только по тестам:)
1) В данном случае тесты нужно написать и на класс льва и на базовый класс автомата. Это два класса, а значит их оба нужно тестировать.
2) Кейсы лучше делать простыми, чем сложную логику в тесте (рандомы вообще лучше не использовать!). Т.е. лучше написать целый набор кейсов на все возможные случаи, чем перебирать их в цикле.
3) Тесты желательно писать на все методы, в которых есть логика.

**Comment by DjonnyD** [comment]
Углубился в познания питона, и вот мой результат, переделал задания и тесты:
https://github.com/2gisprojectT/akulov-aliexpress/tree/master/Lion
fsm_data.py - поведение конечного автомата;
Lion.py - реализация льва
LionTest.py - тесты на классы льва и конечного автомата

**Comment by shiron** [comment]
Комментарии по тестам https://github.com/2gisprojectT/akulov-aliexpress/blob/master/Lion/LionTest.py:
1) Можно не выносить в данном случае для Lion тесты для отдельного метода в каждый отдельный класс. Достаточно одного тестового класса для одного класса с логикой.
2) Если нужно проверить несколько кейсов, то лучше не пихать его в один метод (например, test_lion_find), а сделать три отдельных: test_lion_find_antelope и т.д.

**Comment by DjonnyD** [comment]
https://github.com/2gisprojectT/akulov-aliexpress/blob/master/Lion/LionTest.py
Исправил

**Comment by shiron** [comment]
Окей, закрываю
