### ISSUE TITLE
patterns LeagueOfLegends

### ISSUE THREAD

**Issue by MihaZiK** [2gisprojectT/for-homeworks#60]
Лежат здесь: https://github.com/2gisprojectT/shalakin-leagueoflegends/tree/master/Patterns

**Comment by shiron** [comment]
А все компоненты действительно находятся на одной странице? Или на разных?
Если на разных, то так лучше не делать. Лучше сделать несколько классов, отдельный для каждого типа страницы.

**Comment by MihaZiK** [comment]
C главной переходит на нужную страницу, не совсем понял, что сделать, разделить на Page1, Page2 и т.п. классы?

**Comment by shiron** [comment]
Смотри. Если используются несколько типов разных страниц, то лучше разбить все на разные классы, например: главная страница, страница поиска и т.д. При этом на каждой странице будет свой набор компонент.

**Comment by MihaZiK** [comment]
Исправил

**Comment by shiron** [comment]
Ок, закрываю
