### ISSUE TITLE
Большое задание по паттернам тестирование

### ISSUE THREAD

**Issue by eugeny-dementev** [2gisprojectT/for-homeworks#61]
https://github.com/2gisprojectT/dementyev-lastfm/tree/master/lastfm

Для каждой страницы свой объект Page, которому соответствуют свой набор helpers.

Для некоторых тестов требуется авторизация (auth, home), поэтому в home используются элемнты auth теста.

**Comment by shiron** [comment]
Окей, гуд, закрываю)
