### ISSUE TITLE
Forexfactory tests with patterns

### ISSUE THREAD

**Issue by PunkBASSter** [2gisprojectT/for-homeworks#63]
https://github.com/2gisprojectT/shpilev-forexfactory/tree/master/Forexfactory_Patterns/tests
Тесты:
1. Авторизация позитивный - главная страница;
2. Авторизация негативный - главная страница;
3. Быстрый поиск негативный - главная страница, страница поиска;
4. Обычный поиск позитивный - страница поиска;
5. Обычный поиск негативный - страница поиска;
Тесты сгруппированы в классы по страницам, объекты лежат в отдельных папках со страницами.

Объекты страниц:
Главная:
1. Форма авторизации;
2. Форма быстрого поиска.

Поисковая:
1. Форма поиска;
2. Форма результатов;
3. Форма с ошибкой.

**Comment by shiron** [comment]
Окей, гуд, закрываю)
Маленький коммент на будущее - если есть несколько классов страниц, то обычно тоже делают один базовый, в который выносят потом общую логику.
