### ISSUE TITLE
ДЗ Тесты Habra с использованием компонентов

### ISSUE THREAD

**Issue by beta-tank** [2gisprojectT/for-homeworks#64]
Созданы компоненты для выполнения поисковых запросов и для просмотра результатов выдачи.
Тесты проверяют находжение результатов в различных категориях, а так же их отсутствие.
Всё лежит [здесь](https://github.com/2gisprojectT/komissarov-habrahabr/tree/master/6_selenium_component_habr).

**Comment by shiron** [comment]
Окей, гуд, закрываю)
