### ISSUE TITLE
Coursera.org PagesObjects testing

### ISSUE THREAD

**Issue by la0rg** [2gisprojectT/for-homeworks#65]
<b>Тестирование "курсеры" с использованием данных паттернов.</b>
<i>Описание:</i>
1) Все компоненты наследуются от BaseComponent (обертка для поиска по css-селектору)
2) Все страницы наследуются от BasePage (реализует универсальные методы для работы с любой страницей)
3) В реализации компонентов, все методы подходящие под шаблон "go_*" после выполнения подразумевают переход на другую страницу, для этого возвращают объект страницы на которую переходят.
<a href="https://github.com/2gisprojectT/lanbin-coursera/tree/master/coursera_tests">Линк</a>

**Comment by shiron** [comment]
окей, гуд, закрываю
