### ISSUE TITLE
Patterns for vk.com

### ISSUE THREAD

**Issue by vadim-uvarov** [2gisprojectT/for-homeworks#70]
https://github.com/2gisprojectT/uvarov-vk/tree/master/5)patterns_for_vk

Тесты:
1) Тест отправки текстового сообщения
2) Тест прикрепления фотографии (уже загруженной предварительно)
3) Тест отправки сообщения со смайликом
4) Тест логина с помощью номера телефона
5) Тест логина с помощью email

Очень долго провозился со 2-м тестом, но так и не смог его наладить: реакция Контакта на нажатие фотографии вручную и автоматически разная. Вручную - фото добавляется к письму, автоматически - открывается само фото в альбоме. Еще была проблема была с открытием окна прикрепления фото (меню прикреплений появляется при наведении). Пришлось использовать JavaScript для обращения к невидимому объекту,

Сруктура проекта:
tests - тесты
**page_Dialogue - окно диалога**
    button_add_attachment     -     меню прикреплений
    button_emoticons              -     меню смайликов
    text_box                            -      поле сообщения
**page_listOfDialogues - окно списка диалогов пользователя**
    dialogue_row                 -     один из диалогов
**page_ login - окно логина**
    login_field                       -  поле логина
    password_field               -  поле пароля

**Comment by shiron** [comment]
Все гуд, закрываю.
 Два небольших замечания:
1) Лучше это тоже унести куда-то в пейдж из setUpClass
WebDriverWait(cls.driver, 10).until(EC.presence_of_element_located((By.CSS_SELECTOR, ".left_label.inl_bl")))
2) Поскольку тесты на разный функционал, то лучше их разбить на два отдельных файла, например: login_test.py и send_message_test.py
