### ISSUE TITLE
patterns(info.2gis.ru)

### ISSUE THREAD

**Issue by eltray** [2gisprojectT/for-homeworks#77]
<a href="https://github.com/2gisprojectT/traystor-info2gis/tree/f44ddf05d9afaf66277be0596a99df55e29c79ea/5.HW_patterns(info.2gis.ru)"> HW patterns</a>
<a href= "https://github.com/2gisprojectT/traystor-info2gis/tree/master/1.HW_Lion"> Исправил льва </a>

**Comment by shiron** [comment]
По льву - ок.
Если используется несколько страниц в тестах, то для каждой из них лучше сдать отдельный класс, например FeedabckPage, CompanyPage и т.д. И в тестах использовать уже конкретные страницы.

**Comment by eltray** [comment]
<a href =https://github.com/2gisprojectT/traystor-info2gis/tree/master/5.HW_patterns(info.2gis.ru)> исправил паттерны </a>

**Comment by shiron** [comment]
Гуд, закрываю.
