### ISSUE TITLE
паттерны lingualeo

### ISSUE THREAD

**Issue by julTitova** [2gisprojectT/for-homeworks#79]
Паша, посмотри паттерны lingualeo 
https://github.com/2gisprojectT/titova-lingualeo/tree/master/lingua_patterns

Тестовый файл Test1
проверяются следующие сценарии:
1) Метод test_Search_NotEmpty - осуществляет поиск значения, которое точно есть в базе данных.
2) Метод test_Search_Empty- осуществляет поиск значения, которого точно нет в базе данных.Проверяет, 
что при отсутствии значения в базе выдает соответствующее сообщение.
3) test_Search_DropFilter - осуществляет поиск значения, которого точно нет в базе данных, затем, при выдаче сообщения, сбрасывает
данный фильтр, переходит ко всем темам.\
4) test_Choose_material - проверяет выборку тем, по заданному фильтру "тип сложности темы" (средний).

**Comment by shiron** [comment]
Все гуд. 
Только в тестах лучше добавить setUp и tearDown,  чтобы не дублировать одинаковые куски кода в начале и закрытие браузера в конце теста.

**Comment by julTitova** [comment]
Паша, добавила методы setUpClass(cls) и tearDownClass(cls) в тестовый файл Test1
https://github.com/2gisprojectT/titova-lingualeo/tree/master/lingua_patterns/helpers

**Comment by shiron** [comment]
Ок, закрываю
