### ISSUE TITLE
Тесты на SeleniumIDE

### ISSUE THREAD

**Issue by e7now** [2gisprojectT/for-homeworks#8]
Выложил тесты, созданные при тестировании pikabu.ru
1. поисковый запрос "щи щи" (реальные, но короткие слова" - 1.txt
2. поисковый запрос "щи" (слишком короткий запрос) - 2.txt
3. поисковый запрос "ываываывавы" (несуществующее слово) - 3.txt
TS - набор тестов (test suite)
https://github.com/2gisprojectT/semenov-pikabu/tree/master/test-suit%20pikabu.ru%20111014

**Comment by shiron** [comment]
По набору тестов - ок. Добавь к ним какие-нибудь проверки (это же тесты!), а в Selenium IDE тоже есть asserts.

**Comment by e7now** [comment]
Добавил.

**Comment by shiron** [comment]
Окей, закрываю.
