### ISSUE TITLE
Load testing lastfm

### ISSUE THREAD

**Issue by eugeny-dementev** [2gisprojectT/for-homeworks#80]
Тестирование сайт по сценарию:
- зайти на сайт
- поиск песню
- зайти на страницу песни

https://github.com/2gisprojectT/dementyev-lastfm/tree/master/tank
Результаты тестирования в report html-файле созданным танком, в отчете docx и на сайте loadosophia по ссылке http://loadosophia.org/examples/178826/

Настройки танка файле load.ini

**Comment by shiron** [comment]
Ок, гуд, закрываю
