### ISSUE TITLE
ДЗ - ЛЕВ

### ISSUE THREAD

**Issue by eltray** [2gisprojectT/for-homeworks#9]
Наговнокодил))
https://github.com/2gisprojectT/traystor-info2gis/tree/master/HW_Lion

**Comment by shiron** [comment]
Хм, по тестам нужно большее покрытие, чем один тест)

**Comment by eltray** [comment]
Исправил
https://github.com/2gisprojectT/traystor-info2gis/tree/master/HW_Lion/1.1_Lion

**Comment by shiron** [comment]
Два - это тоже мало)
В идеале юнит-тесты покрывают все методы тестируемого класса, проверяя его на всевозможных случаях.

**Comment by eltray** [comment]
<a href="https://github.com/2gisprojectT/traystor-info2gis/tree/master/1.HW_Lion"> Исправил льва </a>

**Comment by shiron** [comment]
Ок, закрываю
